cnf: minor fixes in command_not_found_handle{,r}() for bash and zsh
If pk-command-not-found is not run:
- Let command_not_found_handle() output to stderr, as bash would do.
- Use printf to output instead of echo to avoid issues with
  backslashes, also omit ': ' if $1 is empty or not set.
- Don't let command_not_found_handler() output anything, zsh does this
  for us.

This file was partly 'set -u' safe, now it's completly 'set -u' safe.

Ensure that command_not_found_handler() always returns false as it
should - you never know which future changes happen in the wrapped
command_not_found_handle().

The reason for the different name and the different behaviour is that
the people on the zsh-workers list did not want to copy a name they
considered to be wrong.  What they did copy from bash (possibly from a
downstream) was the initial suboptimal behaviour of
command_not_found_handle(), which later was changed to provide a more
flexible interface.

diff --git a/contrib/command-not-found/PackageKit.sh.in b/contrib/command-not-found/PackageKit.sh.in
--- a/contrib/command-not-found/PackageKit.sh.in
+++ b/contrib/command-not-found/PackageKit.sh.in
@@ -26,17 +26,16 @@ command_not_found_handle () {
 	if [ $runcnf -eq 1 ]; then
 		@LIBEXECDIR@/pk-command-not-found "$@"
 		retval=$?
-	else
-		local shell=`basename "$SHELL"`
-		echo "$shell: $1: command not found"
+	elif [[ -n "${BASH_VERSION-}" ]]; then
+		printf >&2 'bash: %scommand not found\n' "${1:+$1: }"
 	fi
 
 	# return success or failure
 	return $retval
 }
 
-if [ -n "$ZSH_VERSION" ]; then
+if [[ -n "${ZSH_VERSION-}" ]]; then
 	command_not_found_handler () {
-		command_not_found_handle "$@"
+		command_not_found_handle "$@" && return 127
 	}
 fi
